FROM ghcr.io/astral-sh/uv:python3.14-bookworm-slim

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

COPY pyproject.toml uv.lock README.md ./

RUN uv sync --frozen --no-dev --no-install-project

COPY src/inference ./src/inference

RUN uv sync --frozen --no-dev

EXPOSE 8080

CMD ["sh", "-c", "uv run --no-sync fastapi run src/inference/api.py --host 0.0.0.0 --port ${PORT:-8080}"]