[project]
name = "i-ba-mlops-mm-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.3.3",
    "fastapi[standard]>=0.136.1",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.9",
    "pandas>=3.0.2",
    "pyarrow>=24.0.0",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "scikit-learn>=1.8.0",
    "streamlit>=1.57.0",
    "streamlit-extras>=1.5.0",
    "tabulate>=0.10.0",
    "tqdm>=4.67.3",
    "wandb>=0.26.1",
    "xgboost>=3.2.0",
]

[project.scripts]
update-coin-universe = "utils.extract_supported_coins:main"
feature-batch = "feature_pipeline.batch_pipeline:run_batch_pipeline"
feature-backfill = "feature_pipeline.backfill_pipeline:run_backfill_pipeline"
train-xgboost = "training_pipeline.train_xgboost:main"

[dependency-groups]
dev = [
    "ruff>=0.15.10",
]

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = true
